# EU Conventions Tree Traversal Examples

This notebook shows how to use the LATTICE LLM-guided traversal flow on the EU conventions semantic tree.

It is intentionally example-oriented:
- no gold paths
- no evaluation metrics
- no tests
- just load a tree, run example queries, inspect the traversal, and visualize the prediction tree

Before running the traversal cells, make sure the API key for your selected LLM backend is available in the environment.

In [2]:
from __future__ import annotations

import asyncio
import os
import pickle
import sys
from pathlib import Path


def find_repo_root(start: Path) -> Path:
    current = start.resolve()
    while current != current.parent:
        if (current / "src").exists() and (current / "trees").exists():
            return current
        current = current.parent
    raise RuntimeError("Could not find the repository root from the current working directory.")


REPO_ROOT = find_repo_root(Path.cwd())
SRC_DIR = REPO_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from google.genai import types as genai_types

from hyperparams import HyperParams
from llm_apis import GenAIAPI, OpenAIResponsesAPI, VllmAPI, LocalModelAPI
from prompts import get_traversal_prompt_response_constraint
from tree_construction.build_llm_bottom_up_tree import run_coro_sync
from tree_objects import InferSample, SemanticNode
from utils import compute_node_registry, get_all_leaf_nodes_with_path, post_process, setup_logger, visualize_sample

REPO_ROOT

WindowsPath('C:/Users/jmgil/Desktop/TESE/LATTICE/llm-guided-retrieval')

In [3]:
# Configuration
#
# TREE_PATH prefers the expected EU conventions tree path. The fallback points to
# the tree path produced by the current bottom-up construction notebook in this repo.
default_tree_path = REPO_ROOT / "trees" / "EU" / "eu_conventions_notebook" / "eu_conventions_tree-bottom-up-llm.pkl"
if not default_tree_path.exists():
    default_tree_path = REPO_ROOT / "trees" / "EU" / "codigo_civil_notebook" / "eu_conventions_tree-bottom-up-llm.pkl"

# HyperParams.from_args(...) mirrors the way run.py configures retrieval.
# We pass the required args first, then override/add notebook-specific values.
hp = HyperParams.from_args("--subset fiqa --tree_version eu_conventions_notebook")
hp.TREE_PATH = str(default_tree_path)
hp.DATASET = "EU"
hp.LLM_API_BACKEND = "openai"  # one of: openai, genai, vllm, localModel
hp.LLM = "gpt-5.5" # "google/gemma-2-2b-it"  #"google/gemma-2-2b-it" , "gpt-4.1"
hp.LLM_API_TIMEOUT = 120
hp.LLM_API_MAX_RETRIES = 4
hp.LLM_MAX_CONCURRENT_CALLS = 16
hp.LLM_API_STAGGERING_DELAY = 0.05
hp.VLLM_BASE_URL = "http://localhost:8000/v1"
hp.REASONING_IN_TRAVERSAL_PROMPT = -1
hp.SUBSET = "fiqa"  # chooses the traversal relevance definition
hp.MAX_BEAM_SIZE = 8
hp.SEARCH_WITH_PATH_RELEVANCE = True
hp.NUM_LEAF_CALIB = 0
hp.RELEVANCE_CHAIN_FACTOR = 0.5
hp.MAX_PROMPT_PROTO_SIZE = None
hp.MAX_DOC_DESC_CHAR_LEN = None

LOG_DIR = REPO_ROOT / "results" / "tree_construction"
LOG_DIR.mkdir(parents=True, exist_ok=True)
logger = setup_logger("eu_conventions_traversal_notebook", str(LOG_DIR / "eu_conventions_traversal_notebook.log"))

hp

Log file already exists: C:\Users\jmgil\Desktop\TESE\LATTICE\llm-guided-retrieval\results\tree_construction\eu_conventions_traversal_notebook.log, appending to it.

S=fiqa-TV=eu_conventions_notebook-TPV=5-RInTP=-1-NumLC=10-PlTau=5.0-RCF=0.5-LlmApiB=openai-Llm=gpt-4.1-NumI=20-NumES=1000-MaxBS=2-TP=C:\Users\jmgil\Desktop\TESE\LATTICE\llm-guided-retrieval\trees\EU\eu_conventions_notebook\eu_conventions_tree-bottom-up-llm.pkl-LlmApiB=openai-Llm=gpt-5.5-VBUrl=http:____localhost:8000__v1-RInTP=-1-S=fiqa-MaxBS=8-NumLC=0-RCF=0.5

In [4]:
tree_path = Path(hp.TREE_PATH)
tree_obj = pickle.loads(tree_path.read_bytes())
semantic_root_node = SemanticNode().load_dict(tree_obj) if isinstance(tree_obj, dict) else tree_obj
node_registry = compute_node_registry(semantic_root_node)
all_leaf_nodes = get_all_leaf_nodes_with_path(semantic_root_node)

print(f"Loaded tree from: {tree_path}")
print(f"Total nodes in semantic tree: {len(node_registry)}")
print(f"Total leaf nodes: {len(all_leaf_nodes)}")
print("Root description preview:")
print(semantic_root_node.desc[:800])

Loaded tree from: C:\Users\jmgil\Desktop\TESE\LATTICE\llm-guided-retrieval\trees\EU\eu_conventions_notebook\eu_conventions_tree-bottom-up-llm.pkl
Total nodes in semantic tree: 556
Total leaf nodes: 361
Root description preview:
ROOT Node: This subtree addresses questions about the foundational principles, legal procedures, and organizational structure of the European Union and the European Convention on Human Rights (ECHR). It covers the ECHR's objectives and relationship to broader human rights frameworks, the process for signing EU treaties, the structure and governance of EU institutions, and the rights, procedures, and committees established by EU Protocols. Use this subtree for queries on EU treaty signing, institutional roles, legislative processes, protected rights and freedoms, emergency derogations, committee mechanisms, and family law protections under EU law.. Key topics: ECHR foundational principles; EU treaty signing procedures; EU institutions and governance; EU legislative process; EU Protocol righ

In [5]:
def make_llm_api(hp, logger):
    if hp.LLM_API_BACKEND == "genai":
        llm_api = GenAIAPI(hp.LLM, logger=logger, timeout=hp.LLM_API_TIMEOUT, max_retries=hp.LLM_API_MAX_RETRIES)
    elif hp.LLM_API_BACKEND == "openai":
        llm_api = OpenAIResponsesAPI(hp.LLM, logger=logger, timeout=hp.LLM_API_TIMEOUT, max_retries=hp.LLM_API_MAX_RETRIES, log_api_calls=True)
    elif hp.LLM_API_BACKEND == "vllm":
        llm_api = VllmAPI(hp.LLM, logger=logger, timeout=hp.LLM_API_TIMEOUT, max_retries=hp.LLM_API_MAX_RETRIES, base_url=hp.VLLM_BASE_URL)
    elif hp.LLM_API_BACKEND == "localModel":
        llm_api = LocalModelAPI(hp.LLM, logger=logger, timeout=hp.LLM_API_TIMEOUT, max_retries=hp.LLM_API_MAX_RETRIES, log_api_calls=True)
    else:
        raise ValueError(f"Unknown backend: {hp.LLM_API_BACKEND}")

    llm_api_kwargs = {
        "max_concurrent_calls": hp.LLM_MAX_CONCURRENT_CALLS,
        "response_mime_type": "application/json",
        "response_schema": get_traversal_prompt_response_constraint(bool(hp.REASONING_IN_TRAVERSAL_PROMPT)),
        "staggering_delay": hp.LLM_API_STAGGERING_DELAY,
        "print_summary_report": False,
        "thinking_config": genai_types.ThinkingConfig(thinking_budget=hp.REASONING_IN_TRAVERSAL_PROMPT),
    }

    if hp.LLM_API_BACKEND == "vllm":
        llm_api_kwargs.pop("response_mime_type")
        llm_api_kwargs.pop("thinking_config")
        llm_api_kwargs.pop("response_schema")

    if hp.LLM_API_BACKEND == "openai":
        llm_api_kwargs.pop("response_mime_type")
        llm_api_kwargs.pop("thinking_config")

    return llm_api, llm_api_kwargs


llm_api, llm_api_kwargs = make_llm_api(hp, logger)
print(type(llm_api).__name__)

2026-06-16 00:27:37,903 - eu_conventions_traversal_notebook - INFO - Initialized client for model: gpt-5.5
2026-06-16 00:27:38,805 - eu_conventions_traversal_notebook - INFO - Initialized OpenAI Responses client with model: gpt-5.5 (log_api_calls=True)
2026-06-16 00:27:38,807 - eu_conventions_traversal_notebook - INFO - OpenAI prompt/response log file: stderr.openai_api

OpenAIResponsesAPI

## Example Queries

Pick one of these or write your own EU Convention query in the next cell.

In [6]:
EXAMPLE_QUERIES = [
    "What does Article 6 say about the right to a fair trial?",
    "When can the right to liberty and security be restricted?",
    "What protections does Article 8 give for private and family life?",
    "What does the Convention say about prohibition of torture?",
    "How does Protocol 1 protect property rights?",
    "What are the rules for individual applications to the European Court of Human Rights?",
]

for idx, query in enumerate(EXAMPLE_QUERIES):
    print(f"[{idx}] {query}")

[0] What does Article 6 say about the right to a fair trial?
[1] When can the right to liberty and security be restricted?
[2] What protections does Article 8 give for private and family life?
[3] What does the Convention say about prohibition of torture?
[4] How does Protocol 1 protect property rights?
[5] What are the rules for individual applications to the European Court of Human Rights?

In [7]:
query = EXAMPLE_QUERIES[0]
num_iters = 12
query

'What does Article 6 say about the right to a fair trial?'

In [8]:
def make_sample(query: str) -> InferSample:
    return InferSample(
        semantic_root_node,
        node_registry,
        hp=hp,
        logger=logger,
        query=query,
        gold_paths=[],
        excluded_ids_set=set(),
    )


async def run_one_iteration_async(sample: InferSample):
    inputs = sample.get_step_prompts()
    prompts = [prompt for prompt, _ in inputs]
    slates = [slate for _, slate in inputs]

    raw_responses = await llm_api.run_batch(prompts, **llm_api_kwargs)
    response_jsons = [post_process(output, return_json=True) for output in raw_responses]
    sample.update(slates, response_jsons)
    return raw_responses, response_jsons


def run_one_iteration(sample: InferSample):
    return run_coro_sync(run_one_iteration_async(sample))


def print_frontier(sample: InferSample):
    print("Current beam state paths:")
    for state_path in sample.beam_state_paths:
        node = state_path[-1]
        print(f"  path={node.path} | path_relevance={node.path_relevance:.3f} | desc={node.desc[:180]}")


def print_top_predictions(sample: InferSample, k: int = 5):
    top_preds = sample.get_top_predictions(k=k)
    if not top_preds:
        print("No leaf predictions yet. Increase num_iters.")
        return

    for rank, (node, score) in enumerate(top_preds, start=1):
        print(f"[{rank}] path={node.path} | score={score:.3f} | id={node.id}")
        print(node.desc[:600])
        print("-" * 120)


async def run_query_async(query: str, num_iters: int = 4, detailed_logs: bool = False) -> InferSample:
    sample = make_sample(query)
    if detailed_logs: print(f"Running traversal for query: {query}")
    for step in range(num_iters):
        print(f"\n--- Iteration {step + 1} ---")
        _, response_jsons = await run_one_iteration_async(sample)
        if(detailed_logs): print_frontier(sample)
        if response_jsons:
            first_reasoning = response_jsons[0].get("reasoning", "")
            if(detailed_logs):
                print("\nReasoning preview:")
                print(str(first_reasoning)[:800])
    return sample


def run_query(query: str, num_iters: int = 4, detailed_logs: bool = False) -> InferSample:
    return run_coro_sync(run_query_async(query, num_iters=num_iters, detailed_logs=detailed_logs))

In [9]:
#sample = run_query(query, num_iters=num_iters)

In [10]:
#print_top_predictions(sample, k=5)

## ECtHR Multi-Case Article Retrieval Test

This section loads ECtHR cases, joins each case's fact paragraphs into one LATTICE query, retrieves Convention/Protocol article leaves from the EU conventions tree, and compares the predicted article set with the dataset's multi-label article targets.

The main count is `all_gold_found`: a case is counted as correct when every expected article label appears somewhere in the top retrieved article set. Because a case may involve multiple articles, the table also reports partial matches, precision, recall, and F1.

In [11]:
from llm_rl_playground.ecthr_evaluation import (
    EcthrTraversalEvaluator,
    get_label_names,
    load_ecthr_dataset,
    summarize_ecthr_cases,
)

ecthr_evaluator = EcthrTraversalEvaluator(
    semantic_root_node=semantic_root_node,
    node_registry=node_registry,
    hp=hp,
    logger=logger,
    llm_api=llm_api,
    llm_api_kwargs=llm_api_kwargs,
)

print(type(ecthr_evaluator).__name__)

EcthrTraversalEvaluator

In [12]:
# ECtHR evaluation helpers now live in `llm_rl_playground.ecthr_evaluation`.
# Reuse `ecthr_evaluator.evaluate_ecthr_cases_batched(...)` from any notebook
# after constructing it with that notebook's tree, hp, logger, and llm_api.

In [ ]:
# Configure the ECtHR evaluation run.
# Use split="train" if you want to test quickly on the training set facts,
# or split="test" for the held-out ECtHR Cases test split.
ECTHR_CONFIG = "alleged-violation-prediction"
ECTHR_SPLIT = "train"
N_CASES = 1
NUM_ITERS_PER_CASE = 9
TOP_K_LEAVES = 10
PREDICTION_MIN_SCORE = 0.8  # Try 0.25 or 0.35 for stricter precision filtering.
MAX_PREDICTED_ARTICLES = None  # Lower values usually improve precision and reduce recall.
USE_LLM_SELECTOR = False  # Adds one final LLM call per case to select from LATTICE candidates.

ecthr_dataset = load_ecthr_dataset(split=ECTHR_SPLIT, config=ECTHR_CONFIG)
ecthr_label_names = get_label_names(ecthr_dataset)

print(ecthr_dataset)
print("Label names:", ecthr_label_names)
print("First example labels:", ecthr_dataset[0]["labels"])

results_df, ecthr_results = ecthr_evaluator.evaluate_ecthr_cases_batched(
    ecthr_dataset,
    ecthr_label_names,
    n_cases=N_CASES,
    num_iters=NUM_ITERS_PER_CASE,
    top_k=TOP_K_LEAVES,
    prediction_min_score=PREDICTION_MIN_SCORE,
    max_predicted_articles=MAX_PREDICTED_ARTICLES,
    use_llm_selector=USE_LLM_SELECTOR,
)

results_df

2026-06-16 00:27:43,974 - eu_conventions_traversal_notebook - INFO - Running a batch of 1 prompts...
2026-06-16 00:27:43,980 - eu_conventions_traversal_notebook - INFO - Concurrency limited to 16 parallel calls.

Dataset({
    features: ['facts', 'labels', 'silver_rationales', 'gold_rationales'],
    num_rows: 9000
})
Label names: None
First example labels: ['13', '8']

--- Batched iteration 1/9 (1 cases) ---

Processing batch:   0%|          | 0/1 [00:00<?, ?it/s]

2026-06-16 00:27:58,618 - eu_conventions_traversal_notebook - INFO - Running a batch of 3 prompts...
2026-06-16 00:27:58,619 - eu_conventions_traversal_notebook - INFO - Concurrency limited to 16 parallel calls.

--- Batched iteration 2/9 (1 cases) ---

Processing batch:   0%|          | 0/3 [00:00<?, ?it/s]

2026-06-16 00:28:16,047 - eu_conventions_traversal_notebook - INFO - Running a batch of 8 prompts...
2026-06-16 00:28:16,048 - eu_conventions_traversal_notebook - INFO - Concurrency limited to 16 parallel calls.

--- Batched iteration 3/9 (1 cases) ---

Processing batch:   0%|          | 0/8 [00:00<?, ?it/s]

2026-06-16 00:28:36,498 - eu_conventions_traversal_notebook - INFO - Running a batch of 8 prompts...
2026-06-16 00:28:36,500 - eu_conventions_traversal_notebook - INFO - Concurrency limited to 16 parallel calls.

--- Batched iteration 4/9 (1 cases) ---

Processing batch:   0%|          | 0/8 [00:00<?, ?it/s]

2026-06-16 00:28:50,307 - eu_conventions_traversal_notebook - INFO - Running a batch of 8 prompts...
2026-06-16 00:28:50,308 - eu_conventions_traversal_notebook - INFO - Concurrency limited to 16 parallel calls.

--- Batched iteration 5/9 (1 cases) ---

Processing batch:   0%|          | 0/8 [00:00<?, ?it/s]

2026-06-16 00:29:04,686 - eu_conventions_traversal_notebook - INFO - Running a batch of 8 prompts...
2026-06-16 00:29:04,687 - eu_conventions_traversal_notebook - INFO - Concurrency limited to 16 parallel calls.

--- Batched iteration 6/9 (1 cases) ---

Processing batch:   0%|          | 0/8 [00:00<?, ?it/s]

2026-06-16 00:29:23,459 - eu_conventions_traversal_notebook - INFO - Running a batch of 8 prompts...
2026-06-16 00:29:23,460 - eu_conventions_traversal_notebook - INFO - Concurrency limited to 16 parallel calls.

--- Batched iteration 7/9 (1 cases) ---

Processing batch:   0%|          | 0/8 [00:00<?, ?it/s]

2026-06-16 00:29:45,188 - eu_conventions_traversal_notebook - INFO - Running a batch of 8 prompts...
2026-06-16 00:29:45,190 - eu_conventions_traversal_notebook - INFO - Concurrency limited to 16 parallel calls.

--- Batched iteration 8/9 (1 cases) ---

Processing batch:   0%|          | 0/8 [00:00<?, ?it/s]

2026-06-16 00:30:05,067 - eu_conventions_traversal_notebook - INFO - Running a batch of 8 prompts...
2026-06-16 00:30:05,068 - eu_conventions_traversal_notebook - INFO - Concurrency limited to 16 parallel calls.

--- Batched iteration 9/9 (1 cases) ---

Processing batch:   0%|          | 0/8 [00:00<?, ?it/s]

2026-06-16 00:30:26,781 - eu_conventions_traversal_notebook - INFO - Running a batch of 1 prompts...
2026-06-16 00:30:26,785 - eu_conventions_traversal_notebook - INFO - Concurrency limited to 16 parallel calls.

Processing batch:   0%|          | 0/1 [00:00<?, ?it/s]

================ ECtHR case 0 ================
Gold:      ['article_13', 'article_8']
Predicted:  ['article_8']
Correct(all gold found) : False | Recall: 0.50 | Precision: 1.00 | F1: 0.67
Gold articles removed by selector: 1 ['article_13']

================ Summary ================
 cases_evaluated  any_gold_found  all_gold_found  exact_set_match  mean_gold_removed_by_selector  mean_recall  mean_precision  mean_f1
               1             1.0             0.0              0.0                            1.0          0.5             1.0 0.666667

,case_index,gold,predicted,lattice_predicted,gold_removed_by_selector,gold_removed_by_selector_articles,any_gold_found,all_gold_found,exact_set_match,true_positive,precision,recall,f1
0,0,"[article_13, article_8]",[article_8],"[article_13, article_6, article_8]",1,[article_13],True,False,False,1,1.0,0.5,0.666667

In [14]:
summarize_ecthr_cases(results_df)

,cases_evaluated,any_gold_found,all_gold_found,exact_set_match,mean_gold_removed_by_selector,mean_recall,mean_precision,mean_f1
0,1,1.0,0.0,0.0,1.0,0.5,1.0,0.666667

In [15]:
ecthr_dataset[0]

{'facts': ['11.  At the beginning of the events relevant to the application, K. had a daughter, P., and a son, M., born in 1986 and 1988 respectively. P.’s father is X and M.’s father is V. From March to May 1989 K. was voluntarily hospitalised for about three months, having been diagnosed as suffering from schizophrenia. From August to November 1989 and from December 1989 to March 1990, she was again hospitalised for periods of about three months on account of this illness. In 1991 she was hospitalised for less than a week, diagnosed as suffering from an atypical and undefinable psychosis. It appears that social welfare and health authorities have been in contact with the family since 1989.',
  '12.  The applicants initially cohabited from the summer of 1991 to July 1993. In 1991 both P. and M. were living with them. From 1991 to 1993 K. and X were involved in a custody and access dispute concerning P. In May 1992 a residence order was made transferring custody of P. to X.',
  '13.  K. was again hospitalised from 22 April to 7 May 1992, from 13 May to 10 June 1992, and from 11 to 17 January 1993, on account of psychoses. She was in compulsory care between 15 May and 10 June 1992. According to a medical report dated 15 May 1992, K. was paranoid and psychotic.',
  '14.  On 19 March 1993, according to the social welfare authorities’ records, a discussion took place between a social worker and K.’s mother. K.’s mother said that her daughter’s health condition was really bad and that K. had destroyed a childhood picture of hers, a wedding photo of the mother, broken a glass and “pierced the eyes” of all appearing in the photos. K.’s mother had said that she was tired of the situation, as she did not get any support from the mental health authorities. She added that she was worried and afraid that “again something must happen before K. is admitted to care”.\nOn 24 March 1993 K. was placed under observation with a view to determining whether she should be placed in compulsory psychiatric care, having initially been diagnosed as suffering from psychosis. The conditions for compulsory care were not considered to be met but she remained in voluntary care until 5 May 1993.',
  '15.  Allegedly, X did not allow K., P. and M. to meet. On 11 May 1993, when K. was again pregnant, her access to P. was further limited by an order of the District Court of R. Basing itself on a doctor’s opinion, the court held that the child’s mental development would be endangered if the meetings between P. and K. continued without supervision as had been ordered in 1992.',
  '16.  According to the records of the social welfare authorities, M. showed signs of behavioural problems. On 30 March 1992 a psychologist reported how M. had played with two dolls saying – in very vulgar terms – that they were performing sexual acts. On 17 February 1993 K. was said to have broken a mirror in the presence of M. who had kept repeating: “mummy broke the mirror ...”\nNotes of the social authorities of 24 and 30 March 1993 among others state that games which M. played and pictures he drew were of a destructive nature. According to the notes taken on 30 March, he had lately, while the children were singing together at the day-care nursery, shown immense hatred, threatening “to kill everybody”. The occasions when K. fetched him were described as “unpleasant scenes”, M. shouting and hitting his mother who did not react. It was noted, however, that he no longer played doll games with sexual connotations.',
  '17.  According to the records of the social welfare authorities, a discussion between K., her mother, T. and a number of social and mental-health care officials took place on 31 March 1993, during which it was mentioned that the authorities might have to intervene in M.’s upbringing, from the child-protection point of view, in a more drastic way than had been the case so far. It appeared that in connection with K.’s recent hospitalisation T. had “forcibly” taken her from a restaurant, which had made K. furious, with the consequence that she had thrown things around; for example, the microwave oven had ended up on the floor. T. had said that K. was unable to control herself.',
  '18.  On the following day the child welfare support group, consisting of various social and health authorities, agreed that the aim should be to place M. in a children’s home for three months as an assistance measure of open care under section 14 of the 1983 Child Welfare Act (lastensuojelulaki, barnskyddslag 683/1983 – “the 1983 Act”), during which period psychological examinations of the child would be carried out.',
  '19.  On 3 May 1993 a social welfare official decided on behalf of the Social Welfare Board (perusturvalautakunta, grundtrygghetsnämnden) of S. to place M. in a children’s home for a period of three months. This was to be regarded as a short-term support measure pursuant to the 1983 Act. The applicants had been consulted, together with K.’s mother and sister, on 8 April 1993, in order to find an open-care measure which would be practicable. According to the records of that meeting, no such practical measure had been proposed by any of the participants. The applicants had then been heard again on 21 April 1993 and had not objected to the placing of M. in a children’s home.',
  '20.  In an opinion of 12 May 1993, requested by the Social Welfare Board, doctors M.L. and K.R. considered that K. was not at that time able to care for M., but that her mental state would not necessarily permanently prevent her from caring for him. Doctors M.L. and K.R. worked at the hospital of H., where K. had been cared for since 1991 during the periods indicated above.',
  '21.  On 7 June 1993 it was reported by the social welfare authorities that, when K. and T. had come to the children’s home where M. was staying, the boy had undergone a total change in his behaviour, characterised by anger, hatred, swearing, etc. T. had said that he was really tired of the situation and that in his view K. was in need of hospitalisation. When a visit to the health centre had been suggested to her, she had become very angry.\nAccording to a statement of 22 June 1993 by the children’s home, K. and T. had come to the home on 17 June 1993. While T. had been playing with M., other children had come to tell the staff that K. had asked a 3-year-old girl what her name was. As the girl did not reply, K. had raised her voice and shaken the girl, not letting her go until an older girl had given the child’s name. The other children had been frightened by K.’s behaviour.',
  '22.  On 11 June 1993 the social welfare official who had decided on 3 May 1993 to place M. in a children’s home informed the University Hospital of T. and the local hospital of S. in writing that she was very worried about the health of K. and the baby she was carrying. She requested the hospitals to contact her as soon as K. arrived at the hospital and, more particularly, at the time of the baby’s delivery. She also expressed the wish that health-care professionals should pay special attention to the relationship between the mother and the new-born baby from the very beginning.',
  '23.  On 18 June 1993 K. was taken to a district hospital, where she gave birth to J. on the same day. According to the hospital records, the mother stayed calm during the delivery. After the delivery a written decision concerning an emergency care order was served on the hospital. The child was taken to the children’s ward. The mother’s behaviour in the ward was later found to be somewhat restless but not completely disorderly. The hospital records indicate that she understood the situation and wanted to leave hospital the following day. Medication to prevent the secretion of milk was prescribed. It seems that K. left the hospital on 19 June 1993, that is, the following morning, without any post-natal examination. She went to her mother’s home, where she started pushing an empty pram around the place.',
  '24.  J. was immediately placed in emergency care, pursuant to section 18 of the 1983 Act. After the birth of their child, K. and T. were informed of this decision by two social workers at the hospital of H. The Social Director, who had made the decision on behalf of the Social Welfare Board, noted that K.’s mental state had been unstable during the last stages of her pregnancy. He considered that the baby’s health would be endangered since K. had found out about the plans to place the baby in public care. Lastly, he considered that the baby’s father, T., could not guarantee its development and safety. In addition the Social Director referred to the family’s long-standing difficulties, namely, K.’s serious illness and occasionally uncontrolled emotional reactions which could be traumatic for the children, T.’s inability to care for both J. and K., K.’s reluctance to accept guidance, the impossibility of putting the whole responsibility for J.’s development on T., and the impossibility of providing open-care support measures to the necessary extent. The applicants were not heard prior to the decision. On 24 June 1993 the applicants were notified in writing of the decision to take the new-born baby into public care. The notification was also faxed to K.',
  '25.  On 21 June 1993 the Social Director also placed M. in emergency care, citing principally the same reasons as in his decision of 18 June 1993 concerning J.',
  '26.  The applicants did not appeal against the emergency care orders.',
  '27.  On 21 June 1993 the Social Welfare Board took note of the emergency care orders and prohibited all unsupervised access between K. on the one hand, and J. and M. on the other. The number of supervised visits, however, was not restricted. The Board decided to continue preparations for taking M. and J. into care.',
  '28.  A meeting was held by social workers at the family centre on 21 June 1993, before the arrival of the baby from the hospital and in the absence of the applicants. It is mentioned in the report that there was a plan to prohibit the mother’s visits for a month on the ground that her reactions could not be predicted as she had, for example, broken things at home. After this initial period she would be allowed to visit the baby without restriction, but accompanied by her personal nurse. However, this plan was not implemented. The following entry appears in the register for 24 June: “The mother may come with her personal nurse if she wants. Other visitors not allowed for the time being.”',
  '29.  K. was asked to come with T. to the social welfare office on 22 June 1993 at 11.30 a.m. in order to be informed of the decision of 21 June 1993 by the Social Director concerning M. On 24 June 1993 K. and V. (M.’s biological father) were notified in writing of the decision of 21 June 1993. The notification was also faxed to K.',
  '30.  On 22 June 1993 K. was hospitalised voluntarily at the hospital of H. on account of psychosis, having obtained a referral from a doctor at a health care centre. She was treated there until 30 June 1993.',
  '31.  On 23 June 1993 J. was placed in the family centre. T. visited her the same day.',
  '32.  At the beginning of July 1993 T. left the applicants’ home, having been told by the social welfare officials that he had to break off his relationship with K. “if he wanted to keep” J. The applicants nevertheless continued their relationship.',
  '33.  On 15 July 1993 the Social Welfare Board gave its decisions taking J. and M. into “normal” public care, giving reasons similar to those mentioned in the emergency care orders (see paragraph 24 above), and prolonged the access restriction until 15 September 1993. K. was allowed to see the children only in the company of her personal nurse. The Board essentially considered that K.’s state of health remained unstable; that she was subject to aggressive and uncontrolled emotional moods; and that public care proceedings were a severe mental ordeal for a patient. As regards J., the Board therefore believed that her personal security could be jeopardised if access were to take place without supervision. As regards M., the Board feared that K.’s visits to the children’s home “could no longer be supervised by its staff, which would not be in his interest”. Before the decisions of 15 July 1993 the applicants had been heard and had expressed their objection to the care decisions envisaged.',
  '34.  On 15 July 1993 K. visited both her children, accompanied by her personal nurse. The register indicates that it was “a difficult situation”.',
  '35.  On 19 July 1993 T. moved to the family unit of the family centre with J.',
  '36.  On 20 July 1993 K. was again hospitalised in voluntary care at the open ward of the hospital of H., suffering from psychosis. She left hospital the following day, however. On 26 July 1993 she was placed under observation with a view to determining whether she should be placed in compulsory psychiatric care. On 30 July 1993 she was committed to compulsory psychiatric care. According to the file, her relatives had earlier been worried about her and had contacted the hospital in order to get her into hospital care. They reported that K. had disappeared from her home, where she had behaved in an unsettled and aggressive manner. Her hospitalisation lasted until 27 October 1993, that is, three months.',
  '37.  During the period between 18 June and 31 August 1993 K. visited her children at their respective children’s homes. During the visits she was accompanied by her personal nurse from the hospital, who was in contact with the social welfare authorities and arranged the visits having regard to K.’s state of mental health. According to the centre’s register, she visited J. twice during this period.',
  '38.  According to a statement made by a social worker on 4 August 1993, T. had taken good care of J., first at the hospital until 23 June 1993 and later on at the family centre. It was agreed that J. would stay at the family centre and that T. would visit her every other day. J. would visit her father for the first time from 13 to 15 August 1993, during which time T. would organise her christening. The intention was that the baby could move in with her father later on.',
  '39.  After T.’s paternity had been established on 13 July 1993, T. and K. were granted joint custody of J. on 4 August 1993.',
  '40.  T.’s travel expenses to the centre were paid for by the social welfare authorities. From the centre’s records it can be deduced that T. succeeded in creating a relationship with the baby and learned to take good care of her. The home leaves were spent with T. first at his mother’s house and later in his new home.',
  '41.  On 12 August 1993 the Social Welfare Board referred both public care orders to the County Administrative Court (lääninoikeus, länsrätten) for confirmation, as the applicants had opposed them. In support of its referrals, the Board submitted a statement by a social welfare official dated 25 August 1993, according to which T. would not be able to care both for M. and the new-born J. alone, since K. was living in the same home and had been psychotic for the last four years. T. had been in contact with J. at the children’s home three to four times a week. While staying in a flat attached to a municipal children’s home, he had cared for J. for two whole weeks and had subsequently cared for her three days a week in his new home. The Board had therefore begun investigating whether it would be possible to entrust him with the responsibility for J. with the help of support measures taken by the Board.',
  '42.  On 9 September 1993 the County Administrative Court confirmed the care order concerning J., considering that K. had been mentally ill; that the applicants had had conflicts “as a result of which T. had moved away from their home at the beginning of July 1993”; that because of K.’s illness and the family’s other problems the applicants had been unable to provide J. with adequate care; that the care support provided to the family had not sufficiently improved the family’s situation and that the measures could not be expected to satisfy J.’s care needs. No hearing was held.',
  '43.  On 11 November 1993 the County Administrative Court confirmed the care order concerning M., repeating the reasons put forward in its decision of 9 September concerning J. No hearing was held.',
  '44.  In an appeal to the Supreme Administrative Court (korkein hallinto-oikeus, högsta förvaltningsdomstolen) against the confirmation of the public care order concerning M., the applicants were represented by the Public Legal Adviser (yleinen oikeusavustaja, allmänna rättsbiträdet) of S. The Supreme Administrative Court dismissed the appeal on 23 September 1994.',
  '45.  On the same date the Supreme Administrative Court extended the time allowed for an appeal by K. against the confirmation of the care order made in respect of J.',
  '46.  On 18 October 1994 K. appealed against the care order in respect of J. as confirmed by the County Administrative Court on 9 September 1993. On 21 August 1995 the Supreme Administrative Court granted K. cost-free proceedings as from 1 March 1994, appointed Ms Suomela as her representative and upheld the County Administrative Court’s decision of 9 September 1993.',
  '47.  By a decision of 21 January 1994 the Social Welfare Board placed J. in a foster home in K., a town some 120 km away from the applicants’ home. M. joined her on 7 February 1994. The foster parents had no children of their own. Social welfare officials told the applicants and the foster parents that J.’s and M.’s placement would last “for years”. The applicants had proposed that the children’s public care be implemented in the homes of relatives.',
  '48.  In the meantime, on 15 August 1993, J. was christened in the presence of K., T. and M.',
  '49.  A consultation was held at the children’s home, on 18 August 1993, in the presence of T. According to the records, K.’s mental health was very unstable and her psychiatric treatment was expected to have to be continued for four to five years. T., however, had expressed his hopes that K. and he could, together, take care of J. in the future. It was agreed that J. would stay at the children’s home and would visit T. every week from Thursday until Saturday, beginning on 28 August 1993. T. would visit J. on other days, according to an arrangement to be agreed with the children’s home.',
  '50.  On 14 September 1993 the Social Welfare Board prolonged the access restriction until 15 December 1993.',
  '51.  The following notes of a social welfare official appear among those in the case records of the Social Welfare Board:\n“14 September 1993:\n… 2.  ... In addition, the importance of future access between J. and T. has now been questioned, since J.’s placement in [public foster care] is under preparation. It will be difficult for T. to give up J. ...”\n“13 October 1993:',
  '52.  On 27 October 1993 K. was discharged from the hospital of H.',
  '53.  On 2 February 1994 the Social Welfare Board drew up a plan concerning the implementation of the public care. The applicants’ alternative plan was allegedly ignored. For instance, the children could not meet their maternal grandmother at her home.',
  '54.  After the adoption of the care plan on 2 February 1994, the applicants requested a relaxation of the access restriction. For example, T. had been permitted to see J. only once a month.',
  '55.  On 21 March 1994 the applicants requested, inter alia, that the Social Welfare Board should draw up a public care plan aiming at the reunification of the family.',
  '56.  On 3 May 1994 the social welfare authorities organised a meeting in order to revise the care plan of 2 February 1994. The applicants and their representative did not attend the meeting.',

In [16]:
ecthr_results

[{'case_index': 0,
  'query': 'You are an LLM traversing a semantic knowledge tree of European Convention law.\n\nThe tree is structured as follows:\n- Internal nodes are semantic summaries of legal concepts or clusters of rights.\n- Each internal node summarizes the information contained in its child nodes.\n- Leaf nodes are specific Convention or Protocol articles and their provisions.\n\nGiven the facts of an ECtHR case, traverse the tree from the root toward the most legally relevant leaf articles.\n\nYour task is not to retrieve every article that is semantically related. Your task is to identify the articles most likely to be used in an application before the European Court of Human Rights.\n\nTraversal rules:\n1. First identify the central legal injury in the facts.\n2. Move only into child nodes whose summary directly matches that injury.\n3. Penalize branches that are only factually mentioned, background-related, or speculative.\n4. Prefer branches where the facts show an actual state interference, omission, procedural defect, or lack of remedy.\n5. Continue traversal until you reach the strongest article leaves.\n6. Return only leaf articles whose full path from the root is strongly supported by the facts.\n\nFor each selected article leaf:\n- Give the article number and title.\n- Explain the semantic path that led to it.\n- Explain why it is a primary or secondary article.\n- Retrieve the relevant provision text.\n- Assign a relevance score from 0 to 1.\n\nDo not include weak articles unless they are necessary to explain why they were rejected.\n\nCase facts:\n- 11.  At the beginning of the events relevant to the application, K. had a daughter, P., and a son, M., born in 1986 and 1988 respectively. P.’s father is X and M.’s father is V. From March to May 1989 K. was voluntarily hospitalised for about three months, having been diagnosed as suffering from schizophrenia. From August to November 1989 and from December 1989 to March 1990, she was again hospitalised for periods of about three months on account of this illness. In 1991 she was hospitalised for less than a week, diagnosed as suffering from an atypical and undefinable psychosis. It appears that social welfare and health authorities have been in contact with the family since 1989.\n- 12.  The applicants initially cohabited from the summer of 1991 to July 1993. In 1991 both P. and M. were living with them. From 1991 to 1993 K. and X were involved in a custody and access dispute concerning P. In May 1992 a residence order was made transferring custody of P. to X.\n- 13.  K. was again hospitalised from 22 April to 7 May 1992, from 13 May to 10 June 1992, and from 11 to 17 January 1993, on account of psychoses. She was in compulsory care between 15 May and 10 June 1992. According to a medical report dated 15 May 1992, K. was paranoid and psychotic.\n- 14.  On 19 March 1993, according to the social welfare authorities’ records, a discussion took place between a social worker and K.’s mother. K.’s mother said that her daughter’s health condition was really bad and that K. had destroyed a childhood picture of hers, a wedding photo of the mother, broken a glass and “pierced the eyes” of all appearing in the photos. K.’s mother had said that she was tired of the situation, as she did not get any support from the mental health authorities. She added that she was worried and afraid that “again something must happen before K. is admitted to care”.\nOn 24 March 1993 K. was placed under observation with a view to determining whether she should be placed in compulsory psychiatric care, having initially been diagnosed as suffering from psychosis. The conditions for compulsory care were not considered to be met but she remained in voluntary care until 5 May 1993.\n- 15.  Allegedly, X did not allow K., P. and M. to meet. On 11 May 1993, when K. was again pregnant, her access to P. was further limited by an order of the District Court of R. Basing itself on a doctor’s opinion, the court held that the child’s mental development would be endangered if the meetings between P. and K. continued without supervision as had been ordered in 1992.\n- 16.  According to the records of the social welfare authorities, M. showed signs of behavioural problems. On 30 March 1992 a psychologist reported how M. had played with two dolls saying – in very vulgar terms – that they were performing sexual acts. On 17 February 1993 K. was said to have broken a mirror in the presence of M. who had kept repeating: “mummy broke the mirror ...”\nNotes of the social authorities of 24 and 30 March 1993 among others state that games which M. played and pictures he drew were of a destructive nature. According to the notes taken on 30 March, he had lately, while the children were singing together at the day-care nursery, shown immense hatred, threatening “to kill everybody”. The occasions when K. fetched him were described as “unpleasant scenes”, M. shouting and hitting his mother who did not react. It was noted, however, that he no longer played doll games with sexual connotations.\n- 17.  According to the records of the social welfare authorities, a discussion between K., her mother, T. and a number of social and mental-health care officials took place on 31 March 1993, during which it was mentioned that the authorities might have to intervene in M.’s upbringing, from the child-protection point of view, in a more drastic way than had been the case so far. It appeared that in connection with K.’s recent hospitalisation T. had “forcibly” taken her from a restaurant, which had made K. furious, with the consequence that she had thrown things around; for example, the microwave oven had ended up on the floor. T. had said that K. was unable to control herself.\n- 18.  On the following day the child welfare support group, consisting of various social and health authorities, agreed that the aim should be to place M. in a children’s home for three months as an assistance measure of open care under section 14 of the 1983 Child Welfare Act (lastensuojelulaki, barnskyddslag 683/1983 – “the 1983 Act”), during which period psychological examinations of the child would be carried out.\n- 19.  On 3 May 1993 a social welfare official decided on behalf of the Social Welfare Board (perusturvalautakunta, grundtrygghetsnämnden) of S. to place M. in a children’s home for a period of three months. This was to be regarded as a short-term support measure pursuant to the 1983 Act. The applicants had been consulted, together with K.’s mother and sister, on 8 April 1993, in order to find an open-care measure which would be practicable. According to the records of that meeting, no such practical measure had been proposed by any of the participants. The applicants had then been heard again on 21 April 1993 and had not objected to the placing of M. in a children’s home.\n- 20.  In an opinion of 12 May 1993, requested by the Social Welfare Board, doctors M.L. and K.R. considered that K. was not at that time able to care for M., but that her mental state would not necessarily permanently prevent her from caring for him. Doctors M.L. and K.R. worked at the hospital of H., where K. had been cared for since 1991 during the periods indicated above.\n- 21.  On 7 June 1993 it was reported by the social welfare authorities that, when K. and T. had come to the children’s home where M. was staying, the boy had undergone a total change in his behaviour, characterised by anger, hatred, swearing, etc. T. had said that he was really tired of the situation and that in his view K. was in need of hospitalisation. When a visit to the health centre had been suggested to her, she had become very angry.\nAccording to a statement of 22 June 1993 by the children’s home, K. and T. had come to the home on 17 June 1993. While T. had been playing with M., other children had come to tell the staff that K. had asked a 3-year-old girl what her name was. As the girl did not reply, K. had raised her voice and shaken the girl, not letting her go until an older girl had given the child’s name. The other children had been frightened by K.’s behaviour.\n- 22.  On 11 June 1993 the social welfare official who had decided on 3 May 1993 to place M. in a children’s home informed the University Hospital of T. and the local hospital of S. in writing that she was very worried about the health of K. and the baby she was carrying. She requested the hospitals to contact her as soon as K. arrived at the hospital and, more particularly, at the time of the baby’s delivery. She also expressed the wish that health-care professionals should pay special attention to the relationship between the mother and the new-born baby from the very beginning.\n- 23.  On 18 June 1993 K. was taken to a district hospital, where she gave birth to J. on the same day. According to the hospital records, the mother stayed calm during the delivery. After the delivery a written decision concerning an emergency care order was served on the hospital. The child was taken to the children’s ward. The mother’s behaviour in the ward was later found to be somewhat restless but not completely disorderly. The hospital records indicate that she understood the situation and wanted to leave hospital the following day. Medication to prevent the secretion of milk was prescribed. It seems that K. left the hospital on 19 June 1993, that is, the following morning, without any post-natal examination. She went to her mother’s home, where she started pushing an empty pram around the place.\n- 24.  J. was immediately placed in emergency care, pursuant to section 18 of the 1983 Act. After the birth of their child, K. and T. were informed of this decision by two social workers at the hospital of H. The Social Director, who had made the decision on behalf of the Social Welfare Board, noted that K.’s mental state had been unstable during the last stages of her pregnancy. He considered that the baby’s health would be endangered since K. had found out about the plans to place the baby in public care. Lastly, he considered that the baby’s father, T., could not guarantee its development and safety. In addition the Social Director referred to the family’s long-standing difficulties, namely, K.’s serious illness and occasionally uncontrolled emotional reactions which could be traumatic for the children, T.’s inability to care for both J. and K., K.’s reluctance to accept guidance, the impossibility of putting the whole responsibility for J.’s development on T., and the impossibility of providing open-care support measures to the necessary extent. The applicants were not heard prior to the decision. On 24 June 1993 the applicants were notified in writing of the decision to take the new-born baby into public care. The notification was also faxed to K.\n- 25.  On 21 June 1993 the Social Director also placed M. in emergency care, citing principally the same reasons as in his decision of 18 June 1993 concerning J.\n- 26.  The applicants did not appeal against the emergency care orders.\n- 27.  On 21 June 1993 the Social Welfare Board took note of the emergency care orders and prohibited all unsupervised access between K. on the one hand, and J. and M. on the other. The number of supervised visits, however, was not restricted. The Board decided to continue preparations for taking M. and J. into care.\n- 28.  A meeting was held by social workers at the family centre on 21 June 1993, before the arrival of the baby from the hospital and in the absence of the applicants. It is mentioned in the report that there was a plan to prohibit the mother’s visits for a month on the ground that her reactions could not be predicted as she had, for example, broken things at home. After this initial period she would be allowed to visit the baby without restriction, but accompanied by her personal nurse. However, this plan was not implemented. The following entry appears in the register for 24 June: “The mother may come with her personal nurse if she wants. Other visitors not allowed for the time being.”\n- 29.  K. was asked to come with T. to the social welfare office on 22 June 1993 at 11.30 a.m. in order to be informed of the decision of 21 June 1993 by the Social Director concerning M. On 24 June 1993 K. and V. (M.’s biological father) were notified in writing of the decision of 21 June 1993. The notification was also faxed to K.\n- 30.  On 22 June 1993 K. was hospitalised voluntarily at the hospital of H. on account of psychosis, having obtained a referral from a doctor at a health care centre. She was treated there until 30 June 1993.\n- 31.  On 23 June 1993 J. was placed in the family centre. T. visited her the same day.\n- 32.  At the beginning of July 1993 T. left the applicants’ home, having been told by the social welfare officials that he had to break off his relationship with K. “if he wanted to keep” J. The applicants nevertheless continued their relationship.\n- 33.  On 15 July 1993 the Social Welfare Board gave its decisions taking J. and M. into “normal” public care, giving reasons similar to those mentioned in the emergency care orders (see paragraph 24 above), and prolonged the access restriction until 15 September 1993. K. was allowed to see the children only in the company of her personal nurse. The Board essentially considered that K.’s state of health remained unstable; that she was subject to aggressive and uncontrolled emotional moods; and that public care proceedings were a severe mental ordeal for a patient. As regards J., the Board therefore believed that her personal security co\n- [facts truncated]\n',
  'gold': ['article_13', 'article_8'],
  'predicted': ['article_8'],
  'lattice_predicted': ['article_13', 'article_6', 'article_8'],
  'gold_removed_by_selector': 1,
  'gold_removed_by_selector_articles': ['article_13'],
  'top_rows': [{'rank': 1,
    'score': 0.95,
    'path_score': 0.871640625,
    'parent_score': 0.7932812499999999,
    'node_id': '86aa4de01e1019042ada320afaaa28907511f52d',
    'included': True,
    'articles': ['article_8'],
    'text': 'EU Protocol Section I Art. 8(2) Right to respect for private and family life There shall be no interference by a public authority with the exercise of this right except such as is in accordance with the law and is necessary in a democratic society in the interests of national security, public safety or the economic well-being of the country, for the prevention of disorder or crime, for the protection of health or morals, or for the protection of the rights and freedoms of others.'},
   {'rank': 2,
    'score': 0.9,
    'path_score': 0.846640625,
    'parent_score': 0.7932812499999999,
    'node_id': 'c90a8432e8f73e983c9c24e5d083d44d5bbf6705',
    'included': True,
    'articles': ['article_8'],
    'text': 'EU Protocol Section I Art. 8(1) Right to respect for private and family life Everyone has the right to respect for his private and family life, his home and his correspondence.'},
   {'rank': 3,
    'score': 0.68,
    'path_score': 0.6041406250000001,
    'parent_score': 0.52828125,
    'node_id': 'a9f082f9c3b804efcd1bd935f8159ed5409ddf01',
    'included': True,
    'articles': ['article_6'],
    'text': 'EU Protocol Section I Art. 6(1) Right to a fair trial In the determination of his civil rights and obligations or of any criminal charge against him, everyone is entitled to a fair and public hearing within a reasonable time by an independent and impartial tribunal established by law. Judgment shall be pronounced publicly but the press and public may be excluded from all or part of the trial in the interests of morals, public order or national security in a democratic society, where the interests of juveniles or the protection of the private life of the parties so require, or to the extent strictly necessary in the opinion of the court in special circumstances where publicity would prejudice the interests of justice.'},
   {'rank': 4,
    'score': 0.45,
    'path_score': 0.370625,
    'parent_score': 0.29125,
    'node_id': '0e35c2322bc55d523f9136225d2332d3f7f4fac6',
    'included': True,
    'articles': ['article_13'],
    'text': 'EU Protocol Section I Art. 13(1) Right to an effective remedy Everyone whose rights and freedoms as set forth in this Convention are violated shall have an effective remedy before a national authority notwithstanding that the violation has been committed by persons acting in an official capacity.'},
   {'rank': 5,
    'score': 0.2,
    'path_score': 0.49664062499999995,
    'parent_score': 0.7932812499999999,
    'node_id': '5df0e0131d0a68eb38badfb46e26c8dade0b9781',
    'included': False,
    'articles': ['article_8'],
    'text': 'EU Protocol Section I Art. 8 Right to respect for private and family life'},
   {'rank': 6,
    'score': 0.15,
    'path_score': 0.256640625,
    'parent_score': 0.36328125,
    'node_id': '18379be00311b3115f401e62e08a49f75fb6c761',
    'included': False,
    'articles': ['article_5'],
    'text': 'EU Protocol Section I Art. 5(1) Right to liberty and security Everyone has the right to liberty and security of person. No one shall be deprived of his liberty save in the following cases and in accordance with a procedure prescribed by law: (a) the lawful detention of a person after conviction by a competent court; (b) the lawful arrest or detention of a person for noncompliance with the lawful order of a court or in order to secure the fulfilment of any obligation prescribed by law; (c) the lawful arrest or detention of a person effected for the purpose of bringing him before the competent legal authority on reasonable suspicion of having committed an offence or when it is reasonably considered necessary to prevent his committing an offence or fleeing after having done so; (d) the detent'},
   {'rank': 7,
    'score': 0.15,
    'path_score': 0.1,
    'parent_score': 0.05,
    'node_id': '21e5a3b523bc2ed4ff3a1bff524114cd0b391d3b',
    'included': False,
    'articles': ['article_34'],
    'text': 'EU Protocol s Art. 34(1) Individual applications The Court may receive applications from any person, nongovernmental organisation or group of individuals claiming to be the victim of a violation by one of the High Contracting Parties of the rights set forth in the Convention or the Protocols thereto. The High Contracting Parties undertake not to hinder in any way the effective exercise of this right.'},
   {'rank': 8,
    'score': 0.15,
    'path_score': 0.14500000000000002,
    'parent_score': 0.14,
    'node_id': 'e806e93ada5134ac710d218fa08fa4ddc4c5c177',
    'included': False,
    'articles': ['article_35'],
    'text': 'EU Protocol s Art. 35(1) Admissibility criteria The Court may only deal with the matter after all domestic remedies have been exhausted, according to the generally recognised rules of international law, and within a period of four months from the date on which the final decision was taken.'},
   {'rank': 9,
    'score': 0.12,
    'path_score': 0.11,
    'parent_score': 0.1,
    'node_id': 'f3e8255f6d1e75f1522ca5d66cb9e04e20820592',
    'included': False,
    'articles': ['protocol_7_article_5'],
    'text': 'EU Protocol 7 Art. 5(1) Equality between spouses Spouses shall enjoy equality of rights and responsibilities of a private law character between them, and in their relations with their children, as to marriage, during marriage and in the event of its dissolution. This Article shall not prevent States from taking such measures as are necessary in the interests of the children.'},
   {'rank': 10,
    'score': 0.1,
    'path_score': 0.065,
    'parent_score': 0.03,
    'node_id': '69fac2f4a0fb11fb8f95336959e4ad5ebbad30fe',
    'included': False,
    'articles': ['article_10'],

In [17]:
# Optional: visualize the prediction tree explored by the LLM.
VIS_DIR = REPO_ROOT / "results" / "tree_construction"
VIS_DIR.mkdir(parents=True, exist_ok=True)
html_path = VIS_DIR / "eu_conventions_traversal_prediction_tree.html"

fig = visualize_sample(sample, width=1400, height=900, save_path=str(html_path))
print(html_path)

NameError: name 'sample' is not defined

## Notes

- `num_iters` controls how deep the traversal goes before you inspect results.
- If `print_top_predictions(...)` says there are no leaf predictions yet, increase `num_iters`.
- `hp.SUBSET` controls the relevance definition used inside the traversal prompt. For legal QA-style usage, `fiqa` is usually a reasonable default here.
- `visualize_sample(...)` shows the explored prediction tree, not the static semantic tree structure.
- The default tree path first checks `trees/EU/eu_conventions_notebook/tree-bottom-up-llm.pkl`, then falls back to the existing `trees/EU/codigo_civil_notebook/tree-bottom-up-llm.pkl` path.

- The ECtHR section uses `AUEB-NLP/ecthr_cases` (`alleged-violation-prediction` by default). The case facts are joined into one query and the label list is treated as the expected multi-article target set.